WIKI-1317 : upgrade smartgwt to 6.0
exoplatform/maven-depmgt-pom pull request #38
Opened 2017-05-15 10:39 UTC by MrHanachoo

2017-05-15 14:17 UTC, mgreau requested changes

2017-05-15 14:17 UTC, mgreau commented on pom.xml
> +    <com.smartgwt.version>6.0</com.smartgwt.version>
As explained in [DEP-153](https://jira.exoplatform.org/browse/DEP-153) , the Maven coordinates have changed.
Please update this dependency with 
```
<groupId>com.isomorphic.smartgwt.lgpl</groupId>
<artifactId>smartgwt-lgpl</artifactId>
<version>6.0-p20170514</version>
```

So do not forget to:

1. rename the Maven property to `com.isomorphic.smartgwt.lgpl.version`
2. update the coordinates with the new version / groupId / artifactId
3. re-order both maven property and maven dependency declaration to keep the alphabetical order

thanks

2017-05-16 13:34 UTC, mgreau requested changes

2017-05-16 13:34 UTC, mgreau commented on pom.xml
> +        <groupId>com.isomorphic.smartgwt.lgpl</groupId>
Please re-order the maven dependency declaration to keep the alphabetical order by groupId

2017-05-16 13:34 UTC, mgreau commented on pom.xml
> +    <com.isomorphic.smartgwt.lgpl.version>6.0-p20170514</com.isomorphic.smartgwt.lgpl.version>
Please re-order the maven property  to keep the alphabetical order

2017-05-22 09:55 UTC, MrHanachoo commented on pom.xml
> +    <com.isomorphic.smartgwt.lgpl.version>6.0-p20170514</com.isomorphic.smartgwt.lgpl.version>
done

2017-05-22 09:55 UTC, MrHanachoo commented on pom.xml
> +        <groupId>com.isomorphic.smartgwt.lgpl</groupId>
done

2017-05-22 13:07 UTC, mgreau reviewed
Thanks, please squash the commits so that I can merge this PR.

2017-05-22 13:27 UTC, MrHanachoo commented
@mgreau commits squashed

2017-05-24 15:14 UTC, mgreau approved these changes

2017-05-24 15:16 UTC, merged