Feature/infinispan 8
exoplatform/maven-depmgt-pom pull request #43
Opened 2017-05-24 09:06 UTC by aboughzela

2017-05-26 12:19 UTC, thomasdelhomenie requested changes

2017-05-26 12:19 UTC, thomasdelhomenie commented on pom.xml
> +    <jgroups.version>3.6.7.Final</jgroups.version>
Same remark than in kernel PR : 3.6.12.Final ? 4.0.3.Final ?

2017-05-30 10:41 UTC, aboughzela commented on pom.xml
> +    <jgroups.version>3.6.7.Final</jgroups.version>
Update jgroups version 3.7.13.Final to 3.6.13.Final

2017-05-30 10:41 UTC, aboughzela commented
PR updated

2017-06-01 14:44 UTC, thomasdelhomenie approved these changes

2017-06-14 13:34 UTC, merged